import { ActionId, PlantState, StepResult, TomatoCell, TomatoConfig } from '../types/tomato';
import { clamp, round } from '../utils/math';
export const bucketLabels=['very low','low','balanced','high','excessive'];
export const defaultInitialState:PlantState={day:0,waterLevel:50,nutrientLevel:50,health:70,fruitProgress:0,alive:true,currentCellId:'cell-2-2'};
export function bucketIndex(level:number, gridSize=5){return Math.min(gridSize-1,Math.floor(clamp(level)/ (100/gridSize)));}
export function cellIdForLevels(w:number,n:number,gridSize=5){return `cell-${bucketIndex(w,gridSize)}-${bucketIndex(n,gridSize)}`;}
export function getCell(config:TomatoConfig,w:number,n:number):TomatoCell{return config.cells.find(c=>c.id===cellIdForLevels(w,n,config.gridSize)) ?? config.cells[0];}
function growth(wi:number,ni:number){const danger=(i:number)=>i===0||i===4, low=(i:number)=>i<=1; if(danger(wi)&&danger(ni)) return {h:-15,f:0,t:'Both water and nutrients are in dangerous zones, so health falls sharply.'}; if(danger(wi)||danger(ni)) return {h:-8,f:0,t:'One resource is in a dangerous zone, so health falls.'}; if(wi===2&&ni===2) return {h:2,f:5,t:'Water and nutrients are balanced, so health and fruit progress improve.'}; if(low(wi)||low(ni)) return {h:-3,f:1,t:'A resource is low, so fruit barely grows and health slips.'}; return {h:0,f:2,t:'The plant is acceptable but not ideal, so fruit grows slowly.'};}
export function stepEnvironment(state:PlantState, actionId:ActionId, config:TomatoConfig):StepResult{const previousState={...state}; const action=config.actions[actionId]; const afterAction={waterLevel:clamp(state.waterLevel+action.waterDelta),nutrientLevel:clamp(state.nutrientLevel+action.nutrientDelta)}; const cell=getCell(config,afterAction.waterLevel,afterAction.nutrientLevel); const g=growth(cell.x,cell.y); const rawHealth=state.health+cell.healthDelta+g.h; const rawFruit=state.fruitProgress+cell.fruitDelta+g.f; const nextDay=state.day+1; let alive=rawHealth>0; let terminalReason:string|undefined; if(!alive) terminalReason='The plant died because health reached zero.'; if(cell.terminal){alive=false; terminalReason=`The episode ended because the cell "${cell.label}" is terminal.`;} if(nextDay>=config.harvestDay && alive) terminalReason='The episode ended because harvest day was reached.'; const nextState={day:nextDay,waterLevel:afterAction.waterLevel,nutrientLevel:afterAction.nutrientLevel,health:clamp(rawHealth),fruitProgress:clamp(rawFruit),alive,currentCellId:cell.id}; const done=!alive||nextDay>=config.harvestDay||cell.terminal; const healthDeltaTotal=nextState.health-state.health, fruitDeltaTotal=nextState.fruitProgress-state.fruitProgress; const parts=[`action cost ${action.actionCost}`,`cell reward ${cell.rewardOnEnter}`]; let reward=action.actionCost+cell.rewardOnEnter; const rc=config.rewardConstants; if(config.rewardMode!=='sparse'){const fruitReward=rc.fruitGainMultiplier*Math.max(0,fruitDeltaTotal); const healthTerm=healthDeltaTotal>0?rc.healthGainMultiplier*healthDeltaTotal:rc.stressPenaltyMultiplier*healthDeltaTotal; reward+=fruitReward+healthTerm; parts.push(`fruit gain ${round(fruitReward)}`,`health change ${round(healthTerm)}`);} if(!alive){reward+=rc.deathPenalty; parts.push(`death penalty ${rc.deathPenalty}`);} if(nextDay>=config.harvestDay&&alive){const h=rc.harvestFruitWeight*nextState.fruitProgress+rc.harvestHealthWeight*nextState.health; reward+=h; parts.push(`harvest bonus ${round(h)}`);} reward=round(reward); const plainLanguage=`${action.explanation} Water is now ${afterAction.waterLevel} and nutrients are ${afterAction.nutrientLevel}. The plant entered "${cell.label}". ${cell.explanation} ${g.t} Reward was ${reward}. ${terminalReason??'The episode continues.'}`; return {previousState,nextState,reward,done,terminalReason,explanation:{previousState,action,afterAction,cell,cellEffect:`Cell adds health ${cell.healthDelta}, fruit ${cell.fruitDelta}, reward ${cell.rewardOnEnter}.`,growthEffect:g.t,rewardBreakdown:parts,terminalReason,plainLanguage,healthDeltaTotal,fruitDeltaTotal}};}
