import { ActionId, StepExplanation } from './tomato';
export type Algorithm='Manual Mode'|'TD(0) Prediction'|'SARSA'|'Q-learning'|'Monte Carlo'|'Compare algorithms';
export type VTable=Record<string,number>; export type QTable=Record<string,Record<ActionId,number>>; export type CountTable=Record<string,number>; export type StateActionCountTable=Record<string,Record<ActionId,number>>;
export interface RLParameters{alpha:number;gamma:number;epsilon:number;epsilonDecay:number;minEpsilon:number;optimisticInitialization:boolean;initialV:number;initialQ:number;trainingEpisodes:number;maxStepsPerEpisode:number;seed:number;speed:number}
export interface FormulaDetails{algorithm:Algorithm;symbolic:string;numerical:string;oldValue?:number;reward?:number;gamma?:number;nextValue?:number;target?:number;error?:number;alpha?:number;newValue?:number;stateId?:string;actionId?:ActionId;nextStateId?:string;nextActionId?:ActionId;bestNextActionId?:ActionId;explanation:string}
export interface UpdateLogEntry{ id:string; episode:number; step:number; algorithm:Algorithm; previousStateId:string; action:ActionId; reward:number; nextStateId:string; done:boolean; terminalReason?:string; oldValue?:number; target?:number; error?:number; newValue?:number; explanation:string; stepExplanation:StepExplanation; formula?:FormulaDetails}
export interface EpisodeMetric{episode:number;totalReward:number;length:number;algorithm:Algorithm;terminalReason?:string;harvested:boolean;plantDied:boolean}
export interface EpisodeStep{step:number;previousStateId:string;nextStateId:string;action:ActionId;reward:number;waterLevel:number;nutrientLevel:number;health:number;fruitProgress:number;done:boolean;explanation:string;formulaDetails?:FormulaDetails}
export interface EpisodeTrace{episodeNumber:number;algorithm:Algorithm;totalReward:number;terminalReason?:string;steps:EpisodeStep[]}
